# Generated by Django 5.1.7 on 2025-04-01 16:28

import django.db.models.deletion
import heis_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis_api', '0005_user_driver_license_user_other_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='completed_at',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='estimated_hours',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='elevatortype',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to=heis_api.models.elevator_cert_upload_path),
        ),
        migrations.AddField(
            model_name='elevator',
            name='service_manual',
            field=models.FileField(blank=True, null=True, upload_to=heis_api.models.elevator_manual_upload_path),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('installation', 'Installasjon'), ('service', 'Service'), ('repair', 'Reparasjon'), ('inspection', 'Inspeksjon')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='elevator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='heis_api.elevator'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='priority',
            field=models.CharField(choices=[('low', 'Lav'), ('medium', 'Medium'), ('high', 'Høy'), ('urgent', 'Kritisk')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Venter'), ('in_progress', 'Pågår'), ('completed', 'Fullført'), ('cancelled', 'Kansellert')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
