# Generated by Django 5.1.7 on 2025-04-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis_api', '0006_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
