# Generated by Django 5.1.7 on 2025-04-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis_api', '0008_assignmentchecklist_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='end_date',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='assignment',
            name='checklist_status',
            field=models.JSONField(blank=True, default=dict, help_text='Status for sjekklistepunkter (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='procedure_notes',
            field=models.TextField(blank=True, help_text='Notater fra tekniker under prosedyren', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='procedure_step',
            field=models.IntegerField(blank=True, default=0, help_text='Nåværende steg i heisprosedyren (0=ikke startet)', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('installation', 'Installasjon'), ('service', 'Service'), ('repair', 'Reparasjon'), ('inspection', 'Inspeksjon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='elevator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='heis_api.elevator'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Venter'), ('in_progress', 'Pågår'), ('completed', 'Fullført'), ('cancelled', 'Kansellert')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
