# Generated by Django 5.1.7 on 2025-04-07 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis_api', '0009_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Navn/Beskrivelse')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Detaljert beskrivelse')),
                ('status', models.CharField(choices=[('new', 'Ny'), ('contacted', 'Kontaktet'), ('proposal', 'Tilbud Sendt'), ('negotiation', 'Forhandling'), ('won', 'Vunnet'), ('lost', 'Tapt')], default='new', max_length=20, verbose_name='Status')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimert verdi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sist oppdatert')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='heis_api.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Salgsmulighet',
                'verbose_name_plural': 'Salgsmuligheter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='heis_api.elevator')),
            ],
        ),
    ]
