# Generated by Django 5.1.7 on 2025-04-07 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis_api', '0010_salesopportunity_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Tilbudsnummer')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Utstedelsesdato')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Gyldig til dato')),
                ('status', models.CharField(choices=[('draft', 'Utkast'), ('sent', 'Sendt'), ('accepted', 'Akseptert'), ('rejected', 'Avslått')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Interne notater')),
                ('customer_notes', models.TextField(blank=True, null=True, verbose_name='Notater til kunde')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Totalsum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='heis_api.salesopportunity', verbose_name='Tilhørende Salgsmulighet')),
            ],
            options={
                'verbose_name': 'Tilbud',
                'verbose_name_plural': 'Tilbud',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Beskrivelse/Produkt')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Antall')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Enhetspris')),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Linjesum')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='heis_api.quote', verbose_name='Tilbud')),
            ],
            options={
                'verbose_name': 'Tilbudslinje',
                'verbose_name_plural': 'Tilbudslinjer',
            },
        ),
    ]
