# Generated by Django 5.1.7 on 2025-04-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis_api', '0011_quote_quotelineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Tilbudsnummer'),
        ),
    ]
