# Generated by Django 5.1.7 on 2025-04-08 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis_api', '0012_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Utstedelsesdato'),
        ),
    ]
