# Generated by Django 5.1.7 on 2025-04-08 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis_api', '0013_alter_quote_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotelineitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quotelineitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='quotelineitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='elevatortype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Standard Pris'),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='elevator_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heis_api.elevatortype', verbose_name='Heistype'),
        ),
    ]
