# Generated by Django 5.1.7 on 2025-04-08 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis_api', '0014_remove_quotelineitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ordredato')),
                ('status', models.CharField(choices=[('pending', 'Avventer Behandling'), ('processing', 'Under Behandling'), ('shipped', 'Sendt/Levert'), ('invoiced', 'Fakturert'), ('completed', 'Fullført'), ('cancelled', 'Kansellert')], default='pending', max_length=20, verbose_name='Ordrestatus')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Totalsum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Interne Ordrenotater')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='heis_api.customer', verbose_name='Kunde')),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='heis_api.quote', verbose_name='Basert på Tilbud')),
            ],
            options={
                'verbose_name': 'Ordre',
                'verbose_name_plural': 'Ordrer',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Antall')),
                ('unit_price_at_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Enhetspris ved bestilling')),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Linjesum')),
                ('elevator_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heis_api.elevatortype', verbose_name='Heistype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='heis_api.order', verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Ordrelinje',
                'verbose_name_plural': 'Ordrelinjer',
            },
        ),
    ]
