# Generated by Django 5.1.7 on 2025-04-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis_api', '0015_order_orderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='heis_api.order', verbose_name='Tilhørende Ordre'),
        ),
    ]
