# Generated by Django 5.1.7 on 2025-04-08 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heis_api', '0016_assignment_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Startdato')),
                ('end_date', models.DateField(verbose_name='Sluttdato (inkl.)')),
                ('absence_type', models.CharField(choices=[('sick_leave', 'Sykemelding'), ('vacation', 'Ferie'), ('leave_of_absence', 'Permisjon'), ('public_holiday', 'Helligdag'), ('other', 'Annet')], max_length=20, verbose_name='Type fravær')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beskrivelse/Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL, verbose_name='Ansatt')),
            ],
            options={
                'verbose_name': 'Fravær',
                'verbose_name_plural': 'Fravær',
                'ordering': ['-start_date'],
            },
        ),
    ]
